### PR TITLE
Add new next based documentation

### PR DESCRIPTION
**Pull request by antho1404**
### Description

Add a new documentation where we can have full control and be easily synced with the repo.
For information, this is fixing some issues with gitbook that cannot run locally (making hard to work on the doc) and the sync that is somehow locked to a single account and makes it super hard to release updates.
Also, this will provide a great base to add more to the documentation like:
- component/template storybook
- stuff related to the marketplace template
- graphql sandbox etc...

### How to test

Open the preview

### CODE REVIEW

**Comment by antho1404** [comment]
@EmmanuelDrouin if you could validate that design-wise it's good, and shouldn't take too long
@achampagnedev quick review to check the content and organization hasn't changed
@cpvdeveloper overall setup

**Comment by achampagnedev** [comment]
Looks good to me! and the UI is much better with code highlight + quick copy paste etc.

**Review by achampagnedev — APPROVED** [review]

**Review by cpvdeveloper — APPROVED** [review]
Looks great 🎉 

One very small issue is that some code blocks showing the hook's return value are being prefixed with a semi-column, presumably because one of our eslint rules (but honestly I can't figure out which one).

E.g.
```ts
;[
  (
    offer: {
      id: string
      unitPrice: BigNumberish
    },
    quantity: BigNumberish,
  ) => Promise<void>, // acceptOffer. function to accept an Offer
  {
    activeStep: AcceptOfferStep, // returns different values depending on the current acceptation step
    transactionHash: string | undefined, // returns the transaction hash after transaction has been placed on the blockchain
  },
]
```

**Review by EmmanuelDrouin — APPROVED** [review]

**Comment by antho1404** [comment]
> One very small issue is that some code blocks showing the hook's return value are being prefixed with a semi-column

Yes, this is because of the linter. I think the whole rendering for these results doesn't really make sense anyway, markdown has tables so it might make sense to use this instead or explore other ways to render this information. Added an issue about that https://github.com/liteflow-labs/libraries/issues/77

**Comment by achampagnedev** [comment]
> > One very small issue is that some code blocks showing the hook's return value are being prefixed with a semi-column
> 
> Yes, this is because of the linter. I think the whole rendering for these results doesn't really make sense anyway, markdown has tables so it might make sense to use this instead or explore other ways to render this information. Added an issue about that #77

This was based on the Wagmi docs:

https://wagmi.sh/docs/hooks/useBlockNumber

**Pull request merged**
