### PR TITLE
Added option to see a brand note in the footer

### PR DESCRIPTION
**Pull request by achampagnedev**
### Project organization

- Related https://trello.com/c/YkuTtNtH

### Description

The goal of this PR is to add the option to see a brand note "Powered By" in the Footer
image

added property `showBrandNote` to footer to enable this functionality.

### How to test

See Storybook in the Footer section story `With Brand Note`

https://storybook-components-clsttr3th-liteflow.vercel.app/?path=/story/templates-footer-footer--with-brand-note

### Checklist

- [x] Update related changelogs

### CODE REVIEW

**Review by antho1404 — APPROVED** [review]
If design is good for @EmmanuelDrouin it's good for me. 
Naming might be improved `showBrandNote`, I would have put something more like `showPoweredBy` so there is no mental conversion but not a big issue

**Comment by achampagnedev** [comment]
Just switched naming to `showPoweredBy`

**Comment by EmmanuelDrouin** [comment]
> If design is good for @EmmanuelDrouin it's good for me.

Yep design is good for me

**Comment by EmmanuelDrouin** [comment]
[Defylabs - Marketplace template setup](https://trello.com/c/YkuTtNtH/216-defylabs-marketplace-template-setup)

**Pull request merged**
